# Generated by Django 6.0.1 on 2026-01-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file_path",
            field=models.FileField(blank=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("video", "Video"),
                    ("image", "Image"),
                    ("url", "URL Content"),
                ],
                max_length=20,
            ),
        ),
    ]
