# Generated by Django 6.0.1 on 2026-01-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_uploadedfile_file_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("video", "Video"),
                    ("image", "Image"),
                    ("docx", "Word Document"),
                    ("url", "URL Content"),
                ],
                max_length=20,
            ),
        ),
    ]
