# Generated by Django 6.0.1 on 2026-02-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_uploadedfile_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF"),
                    ("video", "Video"),
                    ("docx", "Word Document"),
                    ("txt", "Text File"),
                ],
                max_length=20,
            ),
        ),
    ]
