# Generated by Django 6.0.1 on 2026-02-10 16:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_alter_uploadedfile_file_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadedfile",
            old_name="uploaded_at",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaded_files",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="session_id",
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="chunks_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file_path",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="file_type",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="processing_status",
            field=models.CharField(default="pending", max_length=100),
        ),
    ]
